"""dbt CLI wrapper for the Data Agent."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path


def run_dbt_command(
    command: str,
    project_dir: str | None = None,
    select: str | None = None,
    extra_args: list[str] | None = None,
) -> dict:
    """Run a dbt command and return structured output."""
    cmd = ["dbt", command]

    if project_dir:
        cmd.extend(["--project-dir", project_dir])
    if select:
        cmd.extend(["--select", select])
    if extra_args:
        cmd.extend(extra_args)

    # Use JSON log format for parseable output
    cmd.extend(["--log-format", "json"])

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

    return {
        "command": " ".join(cmd),
        "exit_code": result.returncode,
        "stdout": result.stdout[-5000:] if len(result.stdout) > 5000 else result.stdout,
        "stderr": result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr,
        "success": result.returncode == 0,
    }


def dbt_run(project_dir: str | None = None, select: str | None = None) -> dict:
    """Run dbt models."""
    return run_dbt_command("run", project_dir=project_dir, select=select)


def dbt_test(project_dir: str | None = None, select: str | None = None) -> dict:
    """Run dbt tests."""
    return run_dbt_command("test", project_dir=project_dir, select=select)


def dbt_compile(project_dir: str | None = None, select: str | None = None) -> dict:
    """Compile dbt models without running them."""
    return run_dbt_command("compile", project_dir=project_dir, select=select)


def dbt_docs_generate(project_dir: str | None = None) -> dict:
    """Generate dbt documentation."""
    return run_dbt_command("docs", project_dir=project_dir, extra_args=["generate"])


def dbt_list_models(project_dir: str | None = None) -> list[str]:
    """List all models in the dbt project."""
    result = run_dbt_command("ls", project_dir=project_dir, extra_args=["--resource-type", "model"])
    if result["success"]:
        return [line for line in result["stdout"].strip().split("\n") if line and not line.startswith("{")]
    return []


def generate_model_sql(
    model_name: str,
    source_table: str,
    columns: list[str],
    transformations: dict[str, str] | None = None,
) -> str:
    """Generate a dbt model SQL file template."""
    cols = []
    for col in columns:
        if transformations and col in transformations:
            cols.append(f"    {transformations[col]} as {col}")
        else:
            cols.append(f"    {col}")

    column_list = ",\n".join(cols)
    return f"""-- Generated by AI Engineer Agent
-- Model: {model_name}

with source as (
    select * from {{{{ source('raw', '{source_table}') }}}}
),

transformed as (
    select
{column_list}
    from source
)

select * from transformed
"""


def generate_schema_yml(models: list[dict]) -> str:
    """Generate a schema.yml file for dbt models."""
    lines = ["version: 2", "", "models:"]
    for model in models:
        lines.append(f"  - name: {model['name']}")
        if model.get("description"):
            lines.append(f"    description: \"{model['description']}\"")
        if model.get("columns"):
            lines.append("    columns:")
            for col in model["columns"]:
                lines.append(f"      - name: {col['name']}")
                if col.get("description"):
                    lines.append(f"        description: \"{col['description']}\"")
                if col.get("tests"):
                    lines.append("        tests:")
                    for test in col["tests"]:
                        lines.append(f"          - {test}")
    return "\n".join(lines) + "\n"
